// TODO: Use helpers for testing to build the response data here

export const POSTStoreRequestBodyExamples = {
  DATA_SENT: {
    companyName: 'TEST COMPANY NAME',
    emails: ['test@company.com'],
    phoneNumber: '+13050001122',
    number: '55',
    street1: 'weston road',
    street2: 'suite 106',
    city: 'Weston',
    state: 'FL',
    zip: '33326',
    country: 'US',
    pin: 12345,
    createdAt: 0,
    updatedAt: 0,
    companyLogoUrl: 'https://picsum.photos/200',
    coverImageUrl: 'https://picsum.photos/200',
    companyType: 'Brick & Mortar',
    companyDescription: 'TEST PURPOSE ONLY',
    fein: 123456789,
    years: 5,
    storeType: 'Online',
    links: ['https://qa.boomcard.net/'],
    _tags: ['TEST'],
    _geoloc: {},
    openingTime: 0,
    closingTime: 0,
    days: ['sun', 'mon', 'tue', 'wed', 'thr', 'fri', 'sat'],
    merchant: {
      uid: 're5OljVl3KObKLopKdxpOQBWPL82',
      name: 'Daniel Steve',
      firstName: 'Daniel',
      lastName: 'Steve',
    },
  },
};
export const PUTStoreByIDRequestBodyExamples = {
  DATA_SENT: {
    _id: '603e712662c87e5e629220d4',
    companyName: 'TEST COMPANY NAME',
    emails: ['test@company.com'],
    phoneNumber: '+13050001122',
    number: '55',
    street1: 'weston road',
    street2: 'suite 106',
    city: 'Weston',
    state: 'FL',
    zip: '33326',
    country: 'US',
    pin: 12345,
    createdAt: 0,
    updatedAt: 0,
    companyLogoUrl: 'https://picsum.photos/200',
    coverImageUrl: 'https://picsum.photos/200',
    companyType: 'Brick & Mortar',
    companyDescription: 'TEST PURPOSE ONLY',
    fein: 123456789,
    years: 5,
    storeType: 'Online',
    links: ['https://qa.boomcard.net/'],
    _tags: ['TEST'],
    _geoloc: {},
    openingTime: 3,
    closingTime: 3,
    days: ['sun', 'mon', 'tue', 'wed', 'thr', 'fri', 'sat'],
    merchant: {
      uid: 're5OljVl3KObKLopKdxpOQBWPL82',
      name: 'Daniel Steve',
      firstName: 'Daniel',
      lastName: 'Steve',
    },
  },
};
